services:
  - type: web
    name: AIShoppingCompanion
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.10
    envVars:
      - key: SERPAPI_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
